[package]
name = "rust_ap_connectivity"
version = "0.1.0"
authors = ["Gyan <gys@softwareag.com>"]
edition = "2018"
[lib]
name = "rust_transport"
crate-type = ["staticlib"]
[dependencies]
libc = "0.2.50"